//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 12:44:46 AM EEST 
//


package fi.passiba.biblestudy.crosswaybible.webservice.client.jaxb.response;



/*
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "passage",
    "copyright"
})
@XmlRootElement(name = "crossway-bible")*/
public class CrosswayBible {

    //@XmlElement(required = true)
    protected Passage passage;
   
    /**
     * Gets the value of the passage property.
     * 
     * @return
     *     possible object is
     *     {@link Passage }
     *     
     */
    public Passage getPassage() {
        return passage;
    }

    /**
     * Sets the value of the passage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Passage }
     *     
     */
    public void setPassage(Passage value) {
        this.passage = value;
    }




}
