//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.21 at 08:31:55 PM EEST 
//


package fi.passiba.biblestudy.crosswaybible.webservice.client.jaxb.response;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}crossref"/>
 *         &lt;element ref="{}begin-chapter"/>
 *         &lt;element ref="{}begin-paragraph"/>
 *         &lt;element ref="{}end-chapter"/>
 *         &lt;element ref="{}end-paragraph"/>
 *         &lt;element ref="{}footnote"/>
 *         &lt;element ref="{}heading"/>
 *         &lt;element ref="{}marker"/>
 *         &lt;element ref="{}verse-num"/>
 *         &lt;element ref="{}woc"/>
 *       &lt;/choice>
 *       &lt;attribute name="unit-id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "verse-unit")
public class VerseUnit {

    @XmlElementRefs({
        @XmlElementRef(name = "woc", type = Woc.class),
        @XmlElementRef(name = "heading", type = JAXBElement.class),
        @XmlElementRef(name = "end-paragraph", type = EndParagraph.class),
        @XmlElementRef(name = "begin-paragraph", type = BeginParagraph.class),
        @XmlElementRef(name = "crossref", type = Crossref.class),
        @XmlElementRef(name = "begin-chapter", type = BeginChapter.class),
        @XmlElementRef(name = "verse-num", type = VerseNum.class),
        @XmlElementRef(name = "end-chapter", type = EndChapter.class),
        @XmlElementRef(name = "footnote", type = Footnote.class),
        @XmlElementRef(name = "marker", type = Marker.class)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "unit-id", required = true)
    protected BigInteger unitId;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Woc }
     * {@link EndParagraph }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link BeginParagraph }
     * {@link Crossref }
     * {@link BeginChapter }
     * {@link VerseNum }
     * {@link String }
     * {@link EndChapter }
     * {@link Footnote }
     * {@link Marker }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the unitId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnitId() {
        return unitId;
    }

    /**
     * Sets the value of the unitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnitId(BigInteger value) {
        this.unitId = value;
    }

}
