//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.21 at 08:31:55 PM EEST 
//


package fi.passiba.biblestudy.crosswaybible.webservice.client;

import fi.passiba.biblestudy.crosswaybible.webservice.client.jaxb.request.EvalutateBibleVerseReguest;
import fi.passiba.biblestudy.crosswaybible.webservice.client.jaxb.request.Options;
import fi.passiba.biblestudy.crosswaybible.webservice.client.jaxb.response.*;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Next_QNAME = new QName("", "next");
    private final static QName _Previous_QNAME = new QName("", "previous");
    private final static QName _Copyright_QNAME = new QName("", "copyright");
    private final static QName _Reference_QNAME = new QName("", "reference");
    private final static QName _Heading_QNAME = new QName("", "heading");
    
    
    private final static QName _IncludePassageHorizontalLines_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-passage-horizontal-lines");
    private final static QName _IncludeDoctype_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-doctype");
    private final static QName _IncludeFirstVerseNumbers_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-first-verse-numbers");
    private final static QName _IncludeSurroundingChapters_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-surrounding-chapters");
    private final static QName _IncludeCrossReferences_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-cross-references");
    private final static QName _IncludePassageReferences_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-passage-references");
    private final static QName _IncludeVerseNumbers_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-verse-numbers");
    private final static QName _IncludeHeadingHorizontalLines_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-heading-horizontal-lines");
    private final static QName _LineLength_QNAME = new QName("http://www.crosswaybibles.org/soap/", "line-length");
    private final static QName _IncludeSubheadings_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-subheadings");
    private final static QName _BaseElement_QNAME = new QName("http://www.crosswaybibles.org/soap/", "base-element");
    private final static QName _IncludeHeadings_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-headings");
    private final static QName _Passage_QNAME = new QName("http://www.crosswaybibles.org/soap/", "passage");
    private final static QName _IncludeFootnotes_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-footnotes");
    private final static QName _Key_QNAME = new QName("http://www.crosswaybibles.org/soap/", "key");
    private final static QName _IncludeSimpleEntities_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-simple-entities");
    private final static QName _IncludeLineBreaks_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-line-breaks");
    private final static QName _OutputFormat_QNAME = new QName("http://www.crosswaybibles.org/soap/", "output-format");
    private final static QName _IncludeFootnoteLinks_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-footnote-links");
    private final static QName _IncludeShortCopyright_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-short-copyright");
    private final static QName _IncludeXmlDeclaration_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-xml-declaration");
    private final static QName _IncludeWordIds_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-word-ids");
    private final static QName _IncludeVirtualAttributes_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-virtual-attributes");
    private final static QName _IncludeSelahs_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-selahs");
    private final static QName _IncludeContentType_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-content-type");
    private final static QName _IncludeQuoteEntities_QNAME = new QName("http://www.crosswaybibles.org/soap/", "include-quote-entities");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Woc }
     * 
     */
    public Woc createWoc() {
        return new Woc();
    }

    /**
     * Create an instance of {@link I }
     * 
     */
    public I createI() {
        return new I();
    }

    /**
     * Create an instance of {@link Current }
     * 
     */
    public Current createCurrent() {
        return new Current();
    }

    /**
     * Create an instance of {@link BeginParagraph }
     * 
     */
    public BeginParagraph createBeginParagraph() {
        return new BeginParagraph();
    }

    /**
     * Create an instance of {@link SurroundingChapters }
     * 
     */
    public SurroundingChapters createSurroundingChapters() {
        return new SurroundingChapters();
    }

    /**
     * Create an instance of {@link BeginChapter }
     * 
     */
    public BeginChapter createBeginChapter() {
        return new BeginChapter();
    }

    /**
     * Create an instance of {@link VerseNum }
     * 
     */
    public VerseNum createVerseNum() {
        return new VerseNum();
    }

    /**
     * Create an instance of {@link Footnote }
     * 
     */
    public Footnote createFootnote() {
        return new Footnote();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link Marker }
     * 
     */
    public Marker createMarker() {
        return new Marker();
    }

    /**
     * Create an instance of {@link EndParagraph }
     * 
     */
    public EndParagraph createEndParagraph() {
        return new EndParagraph();
    }

    /**
     * Create an instance of {@link DoPassageQueryResponse }
     * 
     */
    public DoPassageQueryResponse createDoPassageQueryResponse() {
        return new DoPassageQueryResponse();
    }

    /**
     * Create an instance of {@link Crossref }
     * 
     */
    public Crossref createCrossref() {
        return new Crossref();
    }

    /**
     * Create an instance of {@link CrosswayBible }
     * 
     */
    public CrosswayBible createCrosswayBible() {
        return new CrosswayBible();
    }

    /**
     * Create an instance of {@link Return }
     * 
     */
    public Return createReturn() {
        return new Return();
    }

    /**
     * Create an instance of {@link EndChapter }
     * 
     */
    public EndChapter createEndChapter() {
        return new EndChapter();
    }

    /**
     * Create an instance of {@link Passage }
     * 
     */
    public Passage createPassage() {
        return new Passage();
    }

    /**
     * Create an instance of {@link VerseUnit }
     * 
     */
    public VerseUnit createVerseUnit() {
        return new VerseUnit();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "next")
    public JAXBElement<String> createNext(String value) {
        return new JAXBElement<String>(_Next_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "previous")
    public JAXBElement<String> createPrevious(String value) {
        return new JAXBElement<String>(_Previous_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "copyright")
    public JAXBElement<String> createCopyright(String value) {
        return new JAXBElement<String>(_Copyright_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reference")
    public JAXBElement<String> createReference(String value) {
        return new JAXBElement<String>(_Reference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "heading")
    public JAXBElement<String> createHeading(String value) {
        return new JAXBElement<String>(_Heading_QNAME, String.class, null, value);
    }
    
      /**
     * Create an instance of {@link EvalutateBibleVerseReguest }
     * 
     */
    public EvalutateBibleVerseReguest createEvalutateBibleVerseReguest() {
        return new EvalutateBibleVerseReguest();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions(Options option) {
        return option;
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-passage-horizontal-lines")
    public JAXBElement<Boolean> createIncludePassageHorizontalLines(Boolean value) {
        return new JAXBElement<Boolean>(_IncludePassageHorizontalLines_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-doctype")
    public JAXBElement<Boolean> createIncludeDoctype(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeDoctype_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-first-verse-numbers")
    public JAXBElement<Boolean> createIncludeFirstVerseNumbers(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeFirstVerseNumbers_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-surrounding-chapters")
    public JAXBElement<Boolean> createIncludeSurroundingChapters(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeSurroundingChapters_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-cross-references")
    public JAXBElement<Boolean> createIncludeCrossReferences(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeCrossReferences_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-passage-references")
    public JAXBElement<Boolean> createIncludePassageReferences(Boolean value) {
        return new JAXBElement<Boolean>(_IncludePassageReferences_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-verse-numbers")
    public JAXBElement<Boolean> createIncludeVerseNumbers(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeVerseNumbers_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-heading-horizontal-lines")
    public JAXBElement<Boolean> createIncludeHeadingHorizontalLines(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeHeadingHorizontalLines_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "line-length")
    public JAXBElement<BigInteger> createLineLength(BigInteger value) {
        return new JAXBElement<BigInteger>(_LineLength_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-subheadings")
    public JAXBElement<Boolean> createIncludeSubheadings(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeSubheadings_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "base-element")
    public JAXBElement<String> createBaseElement(String value) {
        return new JAXBElement<String>(_BaseElement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-headings")
    public JAXBElement<Boolean> createIncludeHeadings(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeHeadings_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "passage")
    public JAXBElement<String> createPassage(String value) {
        return new JAXBElement<String>(_Passage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-footnotes")
    public JAXBElement<Boolean> createIncludeFootnotes(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeFootnotes_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "key")
    public JAXBElement<String> createKey(String value) {
        return new JAXBElement<String>(_Key_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-simple-entities")
    public JAXBElement<Boolean> createIncludeSimpleEntities(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeSimpleEntities_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-line-breaks")
    public JAXBElement<Boolean> createIncludeLineBreaks(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeLineBreaks_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "output-format")
    public JAXBElement<String> createOutputFormat(String value) {
        return new JAXBElement<String>(_OutputFormat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-footnote-links")
    public JAXBElement<Boolean> createIncludeFootnoteLinks(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeFootnoteLinks_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-short-copyright")
    public JAXBElement<Boolean> createIncludeShortCopyright(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeShortCopyright_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-xml-declaration")
    public JAXBElement<Boolean> createIncludeXmlDeclaration(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeXmlDeclaration_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-word-ids")
    public JAXBElement<Boolean> createIncludeWordIds(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeWordIds_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-virtual-attributes")
    public JAXBElement<Boolean> createIncludeVirtualAttributes(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeVirtualAttributes_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-selahs")
    public JAXBElement<Boolean> createIncludeSelahs(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeSelahs_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-content-type")
    public JAXBElement<Boolean> createIncludeContentType(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeContentType_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.crosswaybibles.org/soap/", name = "include-quote-entities")
    public JAXBElement<Boolean> createIncludeQuoteEntities(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeQuoteEntities_QNAME, Boolean.class, null, value);
    }

}
