//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.20 at 10:17:11 PM EEST 
//


package fi.passiba.biblestudy.crosswaybible.webservice.client;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for outputOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outputOptions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="output-format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="include-passage-references" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-first-verse-numbers" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-verse-numbers" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-footnotes" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-footnote-links" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-headings" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-subheadings" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-surrounding-chapters" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-short-copyright" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-audio-link" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="audio-format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="audio-version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="include-xml-declaration" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-doctype" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-quote-entities" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-simple-entities" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-cross-references" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-line-breaks" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-virtual-attributes" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="base-element" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="include-passage-horizontal-lines" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-heading-horizontal-lines" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-selahs" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-word-ids" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="include-content-type" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="line-length" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="start-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reading-plan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="passage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="begin-character" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correct-capitalization" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="correct-end-punctuation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="end-character" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correct-quotes" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="q" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="words" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phrase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="not-words" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="matches" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="search-text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="link-url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="results-per-page" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outputOptions", propOrder = {

})
public class OutputOptions {

    @XmlElement(name = "output-format", required = true)
    protected String outputFormat;
    @XmlElement(name = "include-passage-references")
    protected boolean includePassageReferences;
    @XmlElement(name = "include-first-verse-numbers")
    protected boolean includeFirstVerseNumbers;
    @XmlElement(name = "include-verse-numbers")
    protected boolean includeVerseNumbers;
    @XmlElement(name = "include-footnotes")
    protected boolean includeFootnotes;
    @XmlElement(name = "include-footnote-links")
    protected boolean includeFootnoteLinks;
    @XmlElement(name = "include-headings")
    protected boolean includeHeadings;
    @XmlElement(name = "include-subheadings")
    protected boolean includeSubheadings;
    @XmlElement(name = "include-surrounding-chapters")
    protected boolean includeSurroundingChapters;
    @XmlElement(name = "include-short-copyright")
    protected boolean includeShortCopyright;
    @XmlElement(name = "include-audio-link")
    protected boolean includeAudioLink;
    @XmlElement(name = "audio-format", required = true)
    protected String audioFormat;
    @XmlElement(name = "audio-version", required = true)
    protected String audioVersion;
    @XmlElement(name = "include-xml-declaration")
    protected boolean includeXmlDeclaration;
    @XmlElement(name = "include-doctype")
    protected boolean includeDoctype;
    @XmlElement(name = "include-quote-entities")
    protected boolean includeQuoteEntities;
    @XmlElement(name = "include-simple-entities")
    protected boolean includeSimpleEntities;
    @XmlElement(name = "include-cross-references")
    protected boolean includeCrossReferences;
    @XmlElement(name = "include-line-breaks")
    protected boolean includeLineBreaks;
    @XmlElement(name = "include-virtual-attributes")
    protected boolean includeVirtualAttributes;
    @XmlElement(name = "base-element", required = true)
    protected String baseElement;
    @XmlElement(name = "include-passage-horizontal-lines")
    protected boolean includePassageHorizontalLines;
    @XmlElement(name = "include-heading-horizontal-lines")
    protected boolean includeHeadingHorizontalLines;
    @XmlElement(name = "include-selahs")
    protected boolean includeSelahs;
    @XmlElement(name = "include-word-ids")
    protected boolean includeWordIds;
    @XmlElement(name = "include-content-type")
    protected boolean includeContentType;
    @XmlElement(name = "line-length", required = true)
    protected BigInteger lineLength;
    @XmlElement(required = true)
    protected String date;
    @XmlElement(name = "start-date", required = true)
    protected String startDate;
    @XmlElement(name = "reading-plan", required = true)
    protected String readingPlan;
    @XmlElement(required = true)
    protected String passage;
    @XmlElement(required = true)
    protected String seed;
    @XmlElement(name = "begin-character", required = true)
    protected String beginCharacter;
    @XmlElement(name = "correct-capitalization")
    protected boolean correctCapitalization;
    @XmlElement(name = "correct-end-punctuation")
    protected boolean correctEndPunctuation;
    @XmlElement(name = "end-character", required = true)
    protected String endCharacter;
    @XmlElement(name = "correct-quotes")
    protected boolean correctQuotes;
    @XmlElement(required = true)
    protected String q;
    @XmlElement(required = true)
    protected String words;
    @XmlElement(required = true)
    protected String phrase;
    @XmlElement(name = "not-words", required = true)
    protected String notWords;
    @XmlElement(required = true)
    protected String scope;
    @XmlElement(required = true)
    protected String matches;
    @XmlElement(name = "search-text", required = true)
    protected String searchText;
    @XmlElement(required = true)
    protected String page;
    @XmlElement(name = "link-url", required = true)
    protected String linkUrl;
    @XmlElement(name = "results-per-page", required = true)
    protected BigInteger resultsPerPage;

    /**
     * Gets the value of the outputFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFormat() {
        return outputFormat;
    }

    /**
     * Sets the value of the outputFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFormat(String value) {
        this.outputFormat = value;
    }

    /**
     * Gets the value of the includePassageReferences property.
     * 
     */
    public boolean isIncludePassageReferences() {
        return includePassageReferences;
    }

    /**
     * Sets the value of the includePassageReferences property.
     * 
     */
    public void setIncludePassageReferences(boolean value) {
        this.includePassageReferences = value;
    }

    /**
     * Gets the value of the includeFirstVerseNumbers property.
     * 
     */
    public boolean isIncludeFirstVerseNumbers() {
        return includeFirstVerseNumbers;
    }

    /**
     * Sets the value of the includeFirstVerseNumbers property.
     * 
     */
    public void setIncludeFirstVerseNumbers(boolean value) {
        this.includeFirstVerseNumbers = value;
    }

    /**
     * Gets the value of the includeVerseNumbers property.
     * 
     */
    public boolean isIncludeVerseNumbers() {
        return includeVerseNumbers;
    }

    /**
     * Sets the value of the includeVerseNumbers property.
     * 
     */
    public void setIncludeVerseNumbers(boolean value) {
        this.includeVerseNumbers = value;
    }

    /**
     * Gets the value of the includeFootnotes property.
     * 
     */
    public boolean isIncludeFootnotes() {
        return includeFootnotes;
    }

    /**
     * Sets the value of the includeFootnotes property.
     * 
     */
    public void setIncludeFootnotes(boolean value) {
        this.includeFootnotes = value;
    }

    /**
     * Gets the value of the includeFootnoteLinks property.
     * 
     */
    public boolean isIncludeFootnoteLinks() {
        return includeFootnoteLinks;
    }

    /**
     * Sets the value of the includeFootnoteLinks property.
     * 
     */
    public void setIncludeFootnoteLinks(boolean value) {
        this.includeFootnoteLinks = value;
    }

    /**
     * Gets the value of the includeHeadings property.
     * 
     */
    public boolean isIncludeHeadings() {
        return includeHeadings;
    }

    /**
     * Sets the value of the includeHeadings property.
     * 
     */
    public void setIncludeHeadings(boolean value) {
        this.includeHeadings = value;
    }

    /**
     * Gets the value of the includeSubheadings property.
     * 
     */
    public boolean isIncludeSubheadings() {
        return includeSubheadings;
    }

    /**
     * Sets the value of the includeSubheadings property.
     * 
     */
    public void setIncludeSubheadings(boolean value) {
        this.includeSubheadings = value;
    }

    /**
     * Gets the value of the includeSurroundingChapters property.
     * 
     */
    public boolean isIncludeSurroundingChapters() {
        return includeSurroundingChapters;
    }

    /**
     * Sets the value of the includeSurroundingChapters property.
     * 
     */
    public void setIncludeSurroundingChapters(boolean value) {
        this.includeSurroundingChapters = value;
    }

    /**
     * Gets the value of the includeShortCopyright property.
     * 
     */
    public boolean isIncludeShortCopyright() {
        return includeShortCopyright;
    }

    /**
     * Sets the value of the includeShortCopyright property.
     * 
     */
    public void setIncludeShortCopyright(boolean value) {
        this.includeShortCopyright = value;
    }

    /**
     * Gets the value of the includeAudioLink property.
     * 
     */
    public boolean isIncludeAudioLink() {
        return includeAudioLink;
    }

    /**
     * Sets the value of the includeAudioLink property.
     * 
     */
    public void setIncludeAudioLink(boolean value) {
        this.includeAudioLink = value;
    }

    /**
     * Gets the value of the audioFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioFormat() {
        return audioFormat;
    }

    /**
     * Sets the value of the audioFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioFormat(String value) {
        this.audioFormat = value;
    }

    /**
     * Gets the value of the audioVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioVersion() {
        return audioVersion;
    }

    /**
     * Sets the value of the audioVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioVersion(String value) {
        this.audioVersion = value;
    }

    /**
     * Gets the value of the includeXmlDeclaration property.
     * 
     */
    public boolean isIncludeXmlDeclaration() {
        return includeXmlDeclaration;
    }

    /**
     * Sets the value of the includeXmlDeclaration property.
     * 
     */
    public void setIncludeXmlDeclaration(boolean value) {
        this.includeXmlDeclaration = value;
    }

    /**
     * Gets the value of the includeDoctype property.
     * 
     */
    public boolean isIncludeDoctype() {
        return includeDoctype;
    }

    /**
     * Sets the value of the includeDoctype property.
     * 
     */
    public void setIncludeDoctype(boolean value) {
        this.includeDoctype = value;
    }

    /**
     * Gets the value of the includeQuoteEntities property.
     * 
     */
    public boolean isIncludeQuoteEntities() {
        return includeQuoteEntities;
    }

    /**
     * Sets the value of the includeQuoteEntities property.
     * 
     */
    public void setIncludeQuoteEntities(boolean value) {
        this.includeQuoteEntities = value;
    }

    /**
     * Gets the value of the includeSimpleEntities property.
     * 
     */
    public boolean isIncludeSimpleEntities() {
        return includeSimpleEntities;
    }

    /**
     * Sets the value of the includeSimpleEntities property.
     * 
     */
    public void setIncludeSimpleEntities(boolean value) {
        this.includeSimpleEntities = value;
    }

    /**
     * Gets the value of the includeCrossReferences property.
     * 
     */
    public boolean isIncludeCrossReferences() {
        return includeCrossReferences;
    }

    /**
     * Sets the value of the includeCrossReferences property.
     * 
     */
    public void setIncludeCrossReferences(boolean value) {
        this.includeCrossReferences = value;
    }

    /**
     * Gets the value of the includeLineBreaks property.
     * 
     */
    public boolean isIncludeLineBreaks() {
        return includeLineBreaks;
    }

    /**
     * Sets the value of the includeLineBreaks property.
     * 
     */
    public void setIncludeLineBreaks(boolean value) {
        this.includeLineBreaks = value;
    }

    /**
     * Gets the value of the includeVirtualAttributes property.
     * 
     */
    public boolean isIncludeVirtualAttributes() {
        return includeVirtualAttributes;
    }

    /**
     * Sets the value of the includeVirtualAttributes property.
     * 
     */
    public void setIncludeVirtualAttributes(boolean value) {
        this.includeVirtualAttributes = value;
    }

    /**
     * Gets the value of the baseElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseElement() {
        return baseElement;
    }

    /**
     * Sets the value of the baseElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseElement(String value) {
        this.baseElement = value;
    }

    /**
     * Gets the value of the includePassageHorizontalLines property.
     * 
     */
    public boolean isIncludePassageHorizontalLines() {
        return includePassageHorizontalLines;
    }

    /**
     * Sets the value of the includePassageHorizontalLines property.
     * 
     */
    public void setIncludePassageHorizontalLines(boolean value) {
        this.includePassageHorizontalLines = value;
    }

    /**
     * Gets the value of the includeHeadingHorizontalLines property.
     * 
     */
    public boolean isIncludeHeadingHorizontalLines() {
        return includeHeadingHorizontalLines;
    }

    /**
     * Sets the value of the includeHeadingHorizontalLines property.
     * 
     */
    public void setIncludeHeadingHorizontalLines(boolean value) {
        this.includeHeadingHorizontalLines = value;
    }

    /**
     * Gets the value of the includeSelahs property.
     * 
     */
    public boolean isIncludeSelahs() {
        return includeSelahs;
    }

    /**
     * Sets the value of the includeSelahs property.
     * 
     */
    public void setIncludeSelahs(boolean value) {
        this.includeSelahs = value;
    }

    /**
     * Gets the value of the includeWordIds property.
     * 
     */
    public boolean isIncludeWordIds() {
        return includeWordIds;
    }

    /**
     * Sets the value of the includeWordIds property.
     * 
     */
    public void setIncludeWordIds(boolean value) {
        this.includeWordIds = value;
    }

    /**
     * Gets the value of the includeContentType property.
     * 
     */
    public boolean isIncludeContentType() {
        return includeContentType;
    }

    /**
     * Sets the value of the includeContentType property.
     * 
     */
    public void setIncludeContentType(boolean value) {
        this.includeContentType = value;
    }

    /**
     * Gets the value of the lineLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineLength() {
        return lineLength;
    }

    /**
     * Sets the value of the lineLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineLength(BigInteger value) {
        this.lineLength = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the readingPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadingPlan() {
        return readingPlan;
    }

    /**
     * Sets the value of the readingPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadingPlan(String value) {
        this.readingPlan = value;
    }

    /**
     * Gets the value of the passage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassage() {
        return passage;
    }

    /**
     * Sets the value of the passage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassage(String value) {
        this.passage = value;
    }

    /**
     * Gets the value of the seed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeed() {
        return seed;
    }

    /**
     * Sets the value of the seed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeed(String value) {
        this.seed = value;
    }

    /**
     * Gets the value of the beginCharacter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeginCharacter() {
        return beginCharacter;
    }

    /**
     * Sets the value of the beginCharacter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeginCharacter(String value) {
        this.beginCharacter = value;
    }

    /**
     * Gets the value of the correctCapitalization property.
     * 
     */
    public boolean isCorrectCapitalization() {
        return correctCapitalization;
    }

    /**
     * Sets the value of the correctCapitalization property.
     * 
     */
    public void setCorrectCapitalization(boolean value) {
        this.correctCapitalization = value;
    }

    /**
     * Gets the value of the correctEndPunctuation property.
     * 
     */
    public boolean isCorrectEndPunctuation() {
        return correctEndPunctuation;
    }

    /**
     * Sets the value of the correctEndPunctuation property.
     * 
     */
    public void setCorrectEndPunctuation(boolean value) {
        this.correctEndPunctuation = value;
    }

    /**
     * Gets the value of the endCharacter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndCharacter() {
        return endCharacter;
    }

    /**
     * Sets the value of the endCharacter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndCharacter(String value) {
        this.endCharacter = value;
    }

    /**
     * Gets the value of the correctQuotes property.
     * 
     */
    public boolean isCorrectQuotes() {
        return correctQuotes;
    }

    /**
     * Sets the value of the correctQuotes property.
     * 
     */
    public void setCorrectQuotes(boolean value) {
        this.correctQuotes = value;
    }

    /**
     * Gets the value of the q property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQ() {
        return q;
    }

    /**
     * Sets the value of the q property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQ(String value) {
        this.q = value;
    }

    /**
     * Gets the value of the words property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWords() {
        return words;
    }

    /**
     * Sets the value of the words property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWords(String value) {
        this.words = value;
    }

    /**
     * Gets the value of the phrase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhrase() {
        return phrase;
    }

    /**
     * Sets the value of the phrase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhrase(String value) {
        this.phrase = value;
    }

    /**
     * Gets the value of the notWords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotWords() {
        return notWords;
    }

    /**
     * Sets the value of the notWords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotWords(String value) {
        this.notWords = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the matches property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatches() {
        return matches;
    }

    /**
     * Sets the value of the matches property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatches(String value) {
        this.matches = value;
    }

    /**
     * Gets the value of the searchText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchText() {
        return searchText;
    }

    /**
     * Sets the value of the searchText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchText(String value) {
        this.searchText = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPage(String value) {
        this.page = value;
    }

    /**
     * Gets the value of the linkUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * Sets the value of the linkUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkUrl(String value) {
        this.linkUrl = value;
    }

    /**
     * Gets the value of the resultsPerPage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResultsPerPage() {
        return resultsPerPage;
    }

    /**
     * Sets the value of the resultsPerPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResultsPerPage(BigInteger value) {
        this.resultsPerPage = value;
    }

}
