//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.21 at 08:31:55 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.crosswaybibles.org/soap/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fi.passiba.biblestudy.crosswaybible.webservice.client.jaxb.request;
