//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.21 at 08:31:55 PM EEST 
//


package fi.passiba.biblestudy.crosswaybible.webservice.client.jaxb.request;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}output-format"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-passage-references"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-first-verse-numbers"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-verse-numbers"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-footnotes"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-footnote-links"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-headings"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-subheadings"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-surrounding-chapters"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-short-copyright"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-xml-declaration"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-doctype"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-quote-entities"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-simple-entities"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-cross-references"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-line-breaks"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-virtual-attributes"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}base-element"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-passage-horizontal-lines"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-heading-horizontal-lines"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-selahs"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-word-ids"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}include-content-type"/>
 *         &lt;element ref="{http://www.crosswaybibles.org/soap/}line-length"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outputFormat",
    "includePassageReferences",
    "includeFirstVerseNumbers",
    "includeVerseNumbers",
    "includeFootnotes",
    "includeFootnoteLinks",
    "includeHeadings",
    "includeSubheadings",
    "includeSurroundingChapters",
    "includeShortCopyright",
    "includeXmlDeclaration",
    "includeDoctype",
    "includeQuoteEntities",
    "includeSimpleEntities",
    "includeCrossReferences",
    "includeLineBreaks",
    "includeVirtualAttributes",
    "baseElement",
    "includePassageHorizontalLines",
    "includeHeadingHorizontalLines",
    "includeSelahs",
    "includeWordIds",
    "includeContentType",
    "lineLength"
})
@XmlRootElement(name = "options")
public class Options {

    @XmlElement(name = "output-format", required = true)
    protected String outputFormat;
    @XmlElement(name = "include-passage-references")
    protected boolean includePassageReferences;
    @XmlElement(name = "include-first-verse-numbers")
    protected boolean includeFirstVerseNumbers;
    @XmlElement(name = "include-verse-numbers")
    protected boolean includeVerseNumbers;
    @XmlElement(name = "include-footnotes")
    protected boolean includeFootnotes;
    @XmlElement(name = "include-footnote-links")
    protected boolean includeFootnoteLinks;
    @XmlElement(name = "include-headings")
    protected boolean includeHeadings;
    @XmlElement(name = "include-subheadings")
    protected boolean includeSubheadings;
    @XmlElement(name = "include-surrounding-chapters")
    protected boolean includeSurroundingChapters;
    @XmlElement(name = "include-short-copyright")
    protected boolean includeShortCopyright;
    @XmlElement(name = "include-xml-declaration")
    protected boolean includeXmlDeclaration;
    @XmlElement(name = "include-doctype")
    protected boolean includeDoctype;
    @XmlElement(name = "include-quote-entities")
    protected boolean includeQuoteEntities;
    @XmlElement(name = "include-simple-entities")
    protected boolean includeSimpleEntities;
    @XmlElement(name = "include-cross-references")
    protected boolean includeCrossReferences;
    @XmlElement(name = "include-line-breaks")
    protected boolean includeLineBreaks;
    @XmlElement(name = "include-virtual-attributes")
    protected boolean includeVirtualAttributes;
    @XmlElement(name = "base-element", required = true)
    protected String baseElement;
    @XmlElement(name = "include-passage-horizontal-lines")
    protected boolean includePassageHorizontalLines;
    @XmlElement(name = "include-heading-horizontal-lines")
    protected boolean includeHeadingHorizontalLines;
    @XmlElement(name = "include-selahs")
    protected boolean includeSelahs;
    @XmlElement(name = "include-word-ids")
    protected boolean includeWordIds;
    @XmlElement(name = "include-content-type")
    protected boolean includeContentType;
    @XmlElement(name = "line-length", required = true)
    protected BigInteger lineLength;

    /**
     * Gets the value of the outputFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFormat() {
        return outputFormat;
    }

    /**
     * Sets the value of the outputFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFormat(String value) {
        this.outputFormat = value;
    }

    /**
     * Gets the value of the includePassageReferences property.
     * 
     */
    public boolean isIncludePassageReferences() {
        return includePassageReferences;
    }

    /**
     * Sets the value of the includePassageReferences property.
     * 
     */
    public void setIncludePassageReferences(boolean value) {
        this.includePassageReferences = value;
    }

    /**
     * Gets the value of the includeFirstVerseNumbers property.
     * 
     */
    public boolean isIncludeFirstVerseNumbers() {
        return includeFirstVerseNumbers;
    }

    /**
     * Sets the value of the includeFirstVerseNumbers property.
     * 
     */
    public void setIncludeFirstVerseNumbers(boolean value) {
        this.includeFirstVerseNumbers = value;
    }

    /**
     * Gets the value of the includeVerseNumbers property.
     * 
     */
    public boolean isIncludeVerseNumbers() {
        return includeVerseNumbers;
    }

    /**
     * Sets the value of the includeVerseNumbers property.
     * 
     */
    public void setIncludeVerseNumbers(boolean value) {
        this.includeVerseNumbers = value;
    }

    /**
     * Gets the value of the includeFootnotes property.
     * 
     */
    public boolean isIncludeFootnotes() {
        return includeFootnotes;
    }

    /**
     * Sets the value of the includeFootnotes property.
     * 
     */
    public void setIncludeFootnotes(boolean value) {
        this.includeFootnotes = value;
    }

    /**
     * Gets the value of the includeFootnoteLinks property.
     * 
     */
    public boolean isIncludeFootnoteLinks() {
        return includeFootnoteLinks;
    }

    /**
     * Sets the value of the includeFootnoteLinks property.
     * 
     */
    public void setIncludeFootnoteLinks(boolean value) {
        this.includeFootnoteLinks = value;
    }

    /**
     * Gets the value of the includeHeadings property.
     * 
     */
    public boolean isIncludeHeadings() {
        return includeHeadings;
    }

    /**
     * Sets the value of the includeHeadings property.
     * 
     */
    public void setIncludeHeadings(boolean value) {
        this.includeHeadings = value;
    }

    /**
     * Gets the value of the includeSubheadings property.
     * 
     */
    public boolean isIncludeSubheadings() {
        return includeSubheadings;
    }

    /**
     * Sets the value of the includeSubheadings property.
     * 
     */
    public void setIncludeSubheadings(boolean value) {
        this.includeSubheadings = value;
    }

    /**
     * Gets the value of the includeSurroundingChapters property.
     * 
     */
    public boolean isIncludeSurroundingChapters() {
        return includeSurroundingChapters;
    }

    /**
     * Sets the value of the includeSurroundingChapters property.
     * 
     */
    public void setIncludeSurroundingChapters(boolean value) {
        this.includeSurroundingChapters = value;
    }

    /**
     * Gets the value of the includeShortCopyright property.
     * 
     */
    public boolean isIncludeShortCopyright() {
        return includeShortCopyright;
    }

    /**
     * Sets the value of the includeShortCopyright property.
     * 
     */
    public void setIncludeShortCopyright(boolean value) {
        this.includeShortCopyright = value;
    }

    /**
     * Gets the value of the includeXmlDeclaration property.
     * 
     */
    public boolean isIncludeXmlDeclaration() {
        return includeXmlDeclaration;
    }

    /**
     * Sets the value of the includeXmlDeclaration property.
     * 
     */
    public void setIncludeXmlDeclaration(boolean value) {
        this.includeXmlDeclaration = value;
    }

    /**
     * Gets the value of the includeDoctype property.
     * 
     */
    public boolean isIncludeDoctype() {
        return includeDoctype;
    }

    /**
     * Sets the value of the includeDoctype property.
     * 
     */
    public void setIncludeDoctype(boolean value) {
        this.includeDoctype = value;
    }

    /**
     * Gets the value of the includeQuoteEntities property.
     * 
     */
    public boolean isIncludeQuoteEntities() {
        return includeQuoteEntities;
    }

    /**
     * Sets the value of the includeQuoteEntities property.
     * 
     */
    public void setIncludeQuoteEntities(boolean value) {
        this.includeQuoteEntities = value;
    }

    /**
     * Gets the value of the includeSimpleEntities property.
     * 
     */
    public boolean isIncludeSimpleEntities() {
        return includeSimpleEntities;
    }

    /**
     * Sets the value of the includeSimpleEntities property.
     * 
     */
    public void setIncludeSimpleEntities(boolean value) {
        this.includeSimpleEntities = value;
    }

    /**
     * Gets the value of the includeCrossReferences property.
     * 
     */
    public boolean isIncludeCrossReferences() {
        return includeCrossReferences;
    }

    /**
     * Sets the value of the includeCrossReferences property.
     * 
     */
    public void setIncludeCrossReferences(boolean value) {
        this.includeCrossReferences = value;
    }

    /**
     * Gets the value of the includeLineBreaks property.
     * 
     */
    public boolean isIncludeLineBreaks() {
        return includeLineBreaks;
    }

    /**
     * Sets the value of the includeLineBreaks property.
     * 
     */
    public void setIncludeLineBreaks(boolean value) {
        this.includeLineBreaks = value;
    }

    /**
     * Gets the value of the includeVirtualAttributes property.
     * 
     */
    public boolean isIncludeVirtualAttributes() {
        return includeVirtualAttributes;
    }

    /**
     * Sets the value of the includeVirtualAttributes property.
     * 
     */
    public void setIncludeVirtualAttributes(boolean value) {
        this.includeVirtualAttributes = value;
    }

    /**
     * Gets the value of the baseElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseElement() {
        return baseElement;
    }

    /**
     * Sets the value of the baseElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseElement(String value) {
        this.baseElement = value;
    }

    /**
     * Gets the value of the includePassageHorizontalLines property.
     * 
     */
    public boolean isIncludePassageHorizontalLines() {
        return includePassageHorizontalLines;
    }

    /**
     * Sets the value of the includePassageHorizontalLines property.
     * 
     */
    public void setIncludePassageHorizontalLines(boolean value) {
        this.includePassageHorizontalLines = value;
    }

    /**
     * Gets the value of the includeHeadingHorizontalLines property.
     * 
     */
    public boolean isIncludeHeadingHorizontalLines() {
        return includeHeadingHorizontalLines;
    }

    /**
     * Sets the value of the includeHeadingHorizontalLines property.
     * 
     */
    public void setIncludeHeadingHorizontalLines(boolean value) {
        this.includeHeadingHorizontalLines = value;
    }

    /**
     * Gets the value of the includeSelahs property.
     * 
     */
    public boolean isIncludeSelahs() {
        return includeSelahs;
    }

    /**
     * Sets the value of the includeSelahs property.
     * 
     */
    public void setIncludeSelahs(boolean value) {
        this.includeSelahs = value;
    }

    /**
     * Gets the value of the includeWordIds property.
     * 
     */
    public boolean isIncludeWordIds() {
        return includeWordIds;
    }

    /**
     * Sets the value of the includeWordIds property.
     * 
     */
    public void setIncludeWordIds(boolean value) {
        this.includeWordIds = value;
    }

    /**
     * Gets the value of the includeContentType property.
     * 
     */
    public boolean isIncludeContentType() {
        return includeContentType;
    }

    /**
     * Sets the value of the includeContentType property.
     * 
     */
    public void setIncludeContentType(boolean value) {
        this.includeContentType = value;
    }

    /**
     * Gets the value of the lineLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineLength() {
        return lineLength;
    }

    /**
     * Sets the value of the lineLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineLength(BigInteger value) {
        this.lineLength = value;
    }

}
