//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 12:44:46 AM EEST 
//


package fi.passiba.biblestudy.crosswaybible.webservice.client.response;


/*@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "crosswayBible"
})
@XmlRootElement(name = "return")*/
public class Return {

    //@XmlElement(name = "crossway-bible", required = true)
    protected CrosswayBible crosswayBible;

    /**
     * Gets the value of the crosswayBible property.
     * 
     * @return
     *     possible object is
     *     {@link CrosswayBible }
     *     
     */
    public CrosswayBible getCrosswayBible() {
        return crosswayBible;
    }

    /**
     * Sets the value of the crosswayBible property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrosswayBible }
     *     
     */
    public void setCrosswayBible(CrosswayBible value) {
        this.crosswayBible = value;
    }

}
