//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 12:44:46 AM EEST 
//


package fi.passiba.biblestudy.crosswaybible.webservice.client.response;

import java.util.ArrayList;
import java.util.List;


/*@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "verseUnit"
})
@XmlRootElement(name = "content")*/
public class Content {

   // @XmlElement(name = "verse-unit", required = true)
    protected List<VerseUnit> verseUnit;

    /**
     * Gets the value of the verseUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verseUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerseUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerseUnit }
     * 
     * 
     */
    public List<VerseUnit> getVerseUnit() {
        if (verseUnit == null) {
            verseUnit = new ArrayList<VerseUnit>();
        }
        return this.verseUnit;
    }

}
