//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.22 at 12:44:46 AM EEST 
//


package fi.passiba.biblestudy.crosswaybible.webservice.client.response;


public class VerseUnit {

/*
        @XmlElementRef(name = "woc", type = Woc.class),
        @XmlElementRef(name = "heading", type = JAXBElement.class),
        @XmlElementRef(name = "verse-num", type = VerseNum.class),
*/
   
    private String heading;
    private Integer versenum;
   
    
    

}
